export const daysArr = [30, 45, 60, 90];

export const noticePeriodKeywords = [
  "Notice period calculator",
  "Notice period calculator India",
  "Notice period calculation formula",
  "Notice period rules",
  "Notice period in India",
  "Notice period resignation",
  "Notice period policy",
  "Notice period meaning",
  "Notice period excel calculator",
  "Notice period calculator with annual leave",
  "90 days notice period calculator",
  "30 days notice period calculator",
  "60 days notice period calculator",
  "Notice period for employees",
  "Notice period for employers",
  "Notice period law India",
  "Notice period buyout calculator",
  "Notice period letter",
  "Notice period sample",
  "Notice period format",
  "Notice period in months",
  "Notice period in days",
  "Notice period for resignation",
  "Notice period for termination",
  "Notice period for probation",
  "Notice period for contract employees",
  "Notice period for permanent employees",
  "Notice period for government employees",
  "Notice period for private employees",
  "Notice period for IT companies",
  "Notice period for HR",
  "Notice period for teachers",
  "Notice period for doctors",
  "Notice period for nurses",
  "Notice period for managers",
  "Notice period for executives",
  "Notice period for freshers",
  "Notice period for experienced employees",
  "Notice period for notice buyout",
  "Notice period calculation India",
  "Notice period calculation excel",
  "Notice period calculation online",
  "Notice period calculation tool",
  "Notice period calculation example",
  "Notice period calculation with leave",
  "Notice period calculation with holidays",
  "Notice period calculation with weekends",
  "Notice period calculation with public holidays",
  "Notice period calculation with earned leave",
  "Notice period calculation with sick leave",
  "Notice period calculation with casual leave",
  "Notice period calculation with paid leave",
  "Notice period calculation with unpaid leave",
  "Notice period calculation with salary",
  "Notice period calculation with bonus",
  "Notice period calculation with gratuity",
  "Notice period calculation with PF",
  "Notice period calculation with ESI",
  "Notice period calculation with tax",
  "Notice period calculation with TDS",
  "Notice period calculation with CTC",
  "Notice period calculation with gross salary",
  "Notice period calculation with net salary",
  "Notice period calculation with variable pay",
  "Notice period calculation with fixed pay",
  "Notice period calculation with incentives",
  "Notice period calculation with commission",
  "Notice period calculation with overtime",
  "Notice period calculation with shift allowance",
  "Notice period calculation with travel allowance",
  "Notice period calculation with medical allowance",
  "Notice period calculation with HRA",
  "Notice period calculation with LTA",
  "Notice period calculation with conveyance",
  "Notice period calculation with special allowance",
  "Notice period calculation with arrears",
  "Notice period calculation with deductions",
  "Notice period calculation with advances",
  "Notice period calculation with loans",
  "Notice period calculation with reimbursements",
  "Notice period calculation with settlements",
  "Notice period calculation with full and final",
  "Notice period calculation with relieving letter",
  "Notice period calculation with experience letter",
  "Notice period calculation with NOC",
  "Notice period calculation with resignation acceptance",
  "Notice period calculation with resignation withdrawal",
  "Notice period calculation with resignation extension",
  "Notice period calculation with resignation cancellation",
  "Notice period calculation with resignation approval",
  "Notice period calculation with resignation rejection",
  "Notice period calculation with resignation notice",
  "Notice period calculation with resignation date",
  "Notice period calculation with last working day",
  "Notice period calculation with joining date",
  "Notice period calculation with appointment letter",
  "Notice period calculation with offer letter",
  "Notice period calculation with employment contract",
  "Notice period calculation with HR policy",
  "Notice period calculation with company policy"
];

export const routes = [
  { path: "/notice-period", label: "Notice Period" },
  { path: "/salary-hike", label: "Salary Hike" },
  { path: "/hike-percentage", label: "Hike Percentage" },
  { path: "/work-experience", label: "Work Experience" },
  { path: "/lwd-checklist", label: "LWD Checklist" },
  { path: "/gratuity", label: "Gratuity Calculator" },
  { path: "/leave-encashment", label: "Leave Encashment" },
  { path: "/ctc-vs-inhand", label: "CTC vs InHand Salary" },
];

export const frequentQuestions = [
  "Can my notice period be reduced or waived?",
  "What happens if I resign without serving the notice period?",
  "Can I use my remaining leave balance during my notice period?",
  "Will I receive my full salary and benefits during the notice period?",
  "Can my employer extend my notice period?",
  "What should I do if my employer is not accepting my resignation?",
  "Can I join a new company during my notice period?",
];

export const salaryHikeFrequentQuestions = [
  "What is the average salary hike in India during appraisals?",
  "How much salary hike can I expect when switching jobs in India?",
  "What is the expected salary hike for freshers and experienced professionals in India?",
  "How does experience impact salary hikes in India?",
  "What are the salary hike trends in India for 2024-25?",
];

export const salaryData = [
  { annual: "1 LPA", monthly: "7,600 - 8,300", yearly: "91,600 - 1,00,000" },
  {
    annual: "1.5 LPA",
    monthly: "11,500 - 12,500",
    yearly: "1,38,600 - 1,50,000",
  },
  {
    annual: "2 LPA",
    monthly: "15,500 - 16,600",
    yearly: "1,85,600 - 1,97,600",
  },
  {
    annual: "2.3 LPA",
    monthly: "17,817 - 19,100",
    yearly: "2,13,000 - 2,27,600",
  },
  {
    annual: "3 LPA",
    monthly: "23,300 - 25,000",
    yearly: "2,79,600 - 2,97,600",
  },
  {
    annual: "3.8 LPA",
    monthly: "29,500 - 31,400",
    yearly: "3,60,800 - 3,77,600",
  },
  {
    annual: "3.9 LPA",
    monthly: "30,350 - 32,300",
    yearly: "3,64,200 - 3,87,600",
  },
  {
    annual: "4 LPA",
    monthly: "31,100 - 33,133",
    yearly: "3,73,600 - 3,97,600",
  },
  {
    annual: "5 LPA",
    monthly: "38,200 - 41,400",
    yearly: "4,67,600 - 4,97,600",
  },
  {
    annual: "5.5 LPA",
    monthly: "42,800 - 45,600",
    yearly: "5,14,600 - 5,47,600",
  },
  {
    annual: "6 LPA",
    monthly: "45,500 - 49,800",
    yearly: "5,61,600 - 5,97,600",
  },
  {
    annual: "7 LPA",
    monthly: "51,000 - 54,600",
    yearly: "6,12,000 - 6,55,200",
  },
  {
    annual: "8 LPA",
    monthly: "57,200 - 63,800",
    yearly: "6,87,400 - 7,65,600",
  },
  {
    annual: "8.5 LPA",
    monthly: "61,400 - 66,384",
    yearly: "7,24,800 - 7,96,700",
  },
  {
    annual: "9 LPA",
    monthly: "63,600 - 70,300",
    yearly: "7,63,200 - 8,43,600",
  },
  {
    annual: "9.2 LPA",
    monthly: "64,900 - 71,800",
    yearly: "7,74,800 - 8,62,400",
  },
  {
    annual: "9.5 LPA",
    monthly: "66,800 - 73,700",
    yearly: "8,00,000 - 8,84,900",
  },
  {
    annual: "9.6 LPA",
    monthly: "67,400 - 74,400",
    yearly: "8,08,000 - 8,93,900",
  },
  {
    annual: "9.8 LPA",
    monthly: "68,700 - 75,700",
    yearly: "8,24,400 - 9,09,000",
  },
  {
    annual: "10 LPA",
    monthly: "70,000 - 77,000",
    yearly: "8,40,000 - 9,25,000",
  },
  {
    annual: "11 LPA",
    monthly: "76,300 - 76,300",
    yearly: "9,15,600 - 10,05,000",
  },
  {
    annual: "11.5 LPA",
    monthly: "79,300 - 87,100",
    yearly: "9,51,600 - 10,45,300",
  },
  {
    annual: "12 LPA",
    monthly: "82,000 - 90,400",
    yearly: "9,84,000 - 10,85,400",
  },
  {
    annual: "13 LPA",
    monthly: "87,500 - 97,100",
    yearly: "10,51,200 - 11,65,000",
  },
  {
    annual: "13.5 LPA",
    monthly: "90,300 - 1,00,400",
    yearly: "10,83,600 - 12,05,700",
  },
  {
    annual: "14 LPA",
    monthly: "93,100 - 1,03,800",
    yearly: "11,17,200 - 12,45,400",
  },
  {
    annual: "15 LPA",
    monthly: "98,600 - 1,10,500",
    yearly: "11,83,200 - 13,26,000",
  },
  {
    annual: "16 LPA",
    monthly: "1,07,100 - 1,17,100",
    yearly: "12,49,600 - 13,99,600",
  },
  {
    annual: "16.5 LPA",
    monthly: "1,06,900 - 1,20,500",
    yearly: "12,82,800 - 14,46,800",
  },
  {
    annual: "17 LPA",
    monthly: "1,09,700 - 1,23,700",
    yearly: "13,16,400 - 14,84,400",
  },
  {
    annual: "17.5 LPA",
    monthly: "1,12,400 - 1,26,700",
    yearly: "13,48,800 - 15,21,000",
  },
  {
    annual: "18 LPA",
    monthly: "1,15,200 - 1,29,800",
    yearly: "13,82,400 - 15,57,700",
  },
  {
    annual: "19 LPA",
    monthly: "1,20,700 - 1,35,900",
    yearly: "14,48,400 - 16,31,000",
  },
  {
    annual: "20 LPA",
    monthly: "1,26,200 - 1,42,000",
    yearly: "15,14,400 - 17,04,300",
  },
  {
    annual: "21 LPA",
    monthly: "1,31,800 - 1,48,100",
    yearly: "15,81,600 - 17,77,600",
  },
  {
    annual: "22 LPA",
    monthly: "1,37,300 - 1,54,200",
    yearly: "16,47,800 - 18,59,900",
  },
  {
    annual: "22.5 LPA",
    monthly: "1,40,100 - 1,57,200",
    yearly: "16,81,200 - 18,87,500",
  },
  {
    annual: "24 LPA",
    monthly: "1,48,300 - 1,66,400",
    yearly: "17,79,600 - 19,97,500",
  },
  {
    annual: "26 LPA",
    monthly: "1,59,400 - 1,78,600",
    yearly: "19,12,800 - 21,43,100",
  },
  {
    annual: "28 LPA",
    monthly: "1,70,500 - 1,90,800",
    yearly: "20,46,000 - 22,90,700",
  },
  {
    annual: "30 LPA",
    monthly: "1,81,500 - 2,03,100",
    yearly: "21,78,000 - 24,37,300",
  },
  {
    annual: "34 LPA",
    monthly: "2,03,600 - 2,27,500",
    yearly: "24,43,200 - 27,30,300",
  },
  {
    annual: "35 LPA",
    monthly: "2,09,100 - 2,33,600",
    yearly: "25,09,200 - 28,03,800",
  },
  {
    annual: "36 LPA",
    monthly: "2,14,700 - 2,39,700",
    yearly: "25,76,400 - 28,77,100",
  },
  {
    annual: "37 LPA",
    monthly: "2,20,200 - 2,45,800",
    yearly: "26,42,400 - 29,50,420",
  },
  {
    annual: "40 LPA",
    monthly: "2,36,800 - 2,74,100",
    yearly: "28,41,600 - 32,89,300",
  },
  {
    annual: "45 LPA",
    monthly: "2,60,400 - 2,94,735",
    yearly: "31,72,800 - 35,36,800",
  },
  {
    annual: "85 LPA",
    monthly: "4,66,000 - 5,39,000",
    yearly: "55,92,000 - 64,68,800",
  },
  {
    annual: "90 LPA",
    monthly: "4,92,500 - 5,69,600",
    yearly: "59,10,000 - 68,35,300",
  },
  {
    annual: "1 Crore",
    monthly: "5,45,100 - 6,30,600",
    yearly: "65,41,200 - 75,68,300",
  },
];

export const SEO_KEYWORDS = [
  "WorkWise",
  "career calculator",
  "notice period calculator",
  "last working day calculator",
  "salary hike estimator",
  "work experience tracker",
  "job resignation tools",
  "job notice period tracker",
  "final working day calculator",
  "salary increment predictor",
  "work anniversary calculator",
  "employment duration calculator",
  "job transition planning",
  "career growth tracker",
  "resignation date calculator",
  "salary negotiation tips",
  "salary growth projection",
  "salary raise estimation",
  "experience certificate tracker",
  "employee resignation helper",
  "notice period extension calculator",
  "HR resignation management",
  "last working day notice",
  "corporate job resignations",
  "job change calculator",
  "salary comparison tool",
  "employee benefits calculator",
  "employment resignation tracker",
  "job leave date calculator",
  "professional career tools",
  "notice period completion",
  "salary planning app",
  "HR job tracking tools",
  "job switch planning",
  "career progression estimator",
  "exit interview preparation",
  "job exit date finder",
  "career decision-making tool",
  "best salary hike tool",
  "salary hike calculation formula",
  "last day of employment tracker",
  "monthly salary raise estimation",
  "employment period estimation",
  "resignation process guide",
  "job resignation planning tool",
  "work experience log",
  "career management platform",
  "career timeline tracker",
  "best career growth calculator",
  "career development planning",
  "HR software for resignations",
  "work history tracker",
  "employment gap calculator",
  "pay raise prediction",
  "compensation increase estimator",
  "financial career planning",
  "salary increment predictor",
  "long-term salary growth",
  "job resignation checklist",
  "best salary raise calculator",
  "professional resignation tools",
  "salary forecast for employees",
  "job change decision-making",
  "work duration estimator",
  "career performance metrics",
  "last day at work estimation",
  "salary appraisal predictor",
  "pay scale evolution",
  "employee transition planning",
  "work tenure calculator",
  "resignation timeline planning",
  "employment tenure tracker",
  "next job salary comparison",
  "HR employee exit tracking",
  "career forecasting calculator",
  "retirement planning estimator",
  "work notice period management",
  "pay raise planning guide",
  "career switch strategy",
  "employment verification tool",
  "corporate resignation strategy",
  "salary improvement planning",
  "job resignation tool online",
  "job market analysis tool",
  "salary package comparison",
  "workforce transition calculator",
  "job shift strategy calculator",
  "employment exit date planner",
  "career performance tracking app",
  "salary adjustment forecast",
  "work history verification",
  "employment planning software",
  "career salary tracker",
  "job benefits assessment",
  "resignation planning software",
  "pay increase calculator",
  "workforce mobility tools",
  "career stability estimation",
  "resignation strategy app",
  "employee career roadmaps",
  "financial job tracking",
  "salary evaluation for professionals",
  "corporate employment tools",
  "HR payroll forecasting",
  "career decision support tool",
  "notice period tracker",
  "last working day estimator",
  "resignation planning calculator",
  "notice period completion guide",
  "salary hike percentage calculator",
  "expected salary raise predictor",
  "salary growth rate calculator",
  "work experience duration calculator",
  "career milestone tracker",
  "employee service length estimator",
  "LWD checklist for employees",
  "last working day process",
  "HR notice period policies",
  "gratuity eligibility checker",
  "gratuity calculation formula",
  "retirement benefits estimator",
  "final settlement calculator",
  "job exit process tracker",
  "HR resignation formalities",
  "career transition planning tool",
  "employment benefits tracker",
  "gratuity payout estimator",
  "work history documentation",
  "HR compliance resignation guide",
  "final paycheck estimation",
  "gratuity claim process",
  "employee exit benefits",
  "severance pay calculator",
  "work tenure benefits estimator",
  "job exit financial planning",
  "gratitude calculator",
];

export const LWD_CHECKLIST = {
  "Before Resigning": [
    "If leaving to go to another company, make sure you have the offer letter in hand.",
    "Print and save important documents like PF UAN, Form 16, tax-related files, and at least 3 months pay slips for future reference.",
    "File any expenses, claims, and reports.",
    "Write a short transition document on projects/accounts you are working on.",
    "Gradually start taking home personal items that are in the office.",
    "Draft your resignation mail/letter in advance.",
  ],
  "Day of Resigning / Serving Notice Period": [
    "Schedule 1-to-1 time with your boss/HR.",
    "Know your notice period and send your resignation mail/letter appropriately.",
    "Agree on your last working day with your boss and HR.",
    "Hand over all your pending tasks or KT to respective collegues.",
    "Continue delivering quality work to leave a lasting positive impression.",
    "Wipe personal information from the laptop and keep backup of you files",
    "Complete your exit interview with your superiors and/or the HR department",
    "Create a list of people you want to talk to in- before leaving.",
    "Collect collegues contacts and network with you collegues for future references",
    "Submit company possessions such as locker keys, ID card, laptop, etc., on your last day.",
    "Send farewell emails.",
  ],
  "After Resigning": [
    "Address important administrative tasks. Ex: Medical Insurance",
    "Follow up with HR for documentation and follow up on outstanding pay and expenses.",
    "Ask for a letter of recommendation from your manager",
    "Update LinkedIn and other social media profiles.",
  ],
};

export const salaryHikeKeywords = [
  "Salary hike calculator",
  "Salary increment calculator",
  "Salary hike percentage calculator",
  "Salary hike India",
  "Salary hike after appraisal",
  "Salary hike after promotion",
  "Salary hike formula",
  "Salary hike calculation",
  "Salary hike estimator",
  "Salary hike tool",
  "Salary hike online",
  "Salary hike for IT professionals",
  "Salary hike for freshers",
  "Salary hike for experienced",
  "Salary hike for government employees",
  "Salary hike for private sector",
  "Salary hike for teachers",
  "Salary hike for engineers",
  "Salary hike for managers",
  "Salary hike for HR",
  "Salary hike for doctors",
  "Salary hike for nurses",
  "Salary hike for executives",
  "Salary hike for sales",
  "Salary hike for finance",
  "Salary hike for marketing",
  "Salary hike for consultants",
  "Salary hike for BPO",
  "Salary hike for MNC",
  "Salary hike for startups",
  "Salary hike for banking",
  "Salary hike for insurance",
  "Salary hike for telecom",
  "Salary hike for pharma",
  "Salary hike for legal",
  "Salary hike for admin",
  "Salary hike for support staff",
  "Salary hike for contract employees",
  "Salary hike for permanent employees",
  "Salary hike for probation",
  "Salary hike for interns",
  "Salary hike for part-time",
  "Salary hike for full-time",
  "Salary hike for remote jobs",
  "Salary hike for on-site jobs",
  "Salary hike for hybrid jobs",
  "Salary hike for women",
  "Salary hike for men",
  "Salary hike for non-binary",
  "Salary hike for disabled",
  "Salary hike for veterans",
  "Salary hike for minorities",
  "Salary hike for expats",
  "Salary hike for NRI",
  "Salary hike for overseas jobs",
  "Salary hike for local jobs",
  "Salary hike for government sector",
  "Salary hike for PSU",
  "Salary hike for central government",
  "Salary hike for state government",
  "Salary hike for defense",
  "Salary hike for police",
  "Salary hike for army",
  "Salary hike for navy",
  "Salary hike for air force",
  "Salary hike for paramilitary",
  "Salary hike for teachers in India",
  "Salary hike for professors",
  "Salary hike for principals",
  "Salary hike for school staff",
  "Salary hike for college staff",
  "Salary hike for university staff",
  "Salary hike for research staff",
  "Salary hike for scientists",
  "Salary hike for IT companies",
  "Salary hike for software engineers",
  "Salary hike for developers",
  "Salary hike for testers",
  "Salary hike for designers",
  "Salary hike for architects",
  "Salary hike for project managers",
  "Salary hike for product managers",
  "Salary hike for business analysts",
  "Salary hike for consultants in India",
  "Salary hike for freelancers",
  "Salary hike for gig workers",
  "Salary hike for blue collar",
  "Salary hike for white collar",
  "Salary hike for pink collar",
  "Salary hike for green collar",
  "Salary hike for gold collar",
  "Salary hike for silver collar",
  "Salary hike for retirees",
  "Salary hike for pensioners",
  "Salary hike for self-employed",
  "Salary hike for entrepreneurs",
  "Salary hike for business owners",
  "Salary hike for startups in India"
];

export const hikePercentageKeywords = [
  "Hike percentage calculator",
  "Salary hike percentage formula",
  "How to calculate hike percentage",
  "Hike percentage after appraisal",
  "Hike percentage after promotion",
  "Hike percentage in India",
  "Hike percentage for IT",
  "Hike percentage for freshers",
  "Hike percentage for experienced",
  "Hike percentage for government employees",
  "Hike percentage for private sector",
  "Hike percentage for teachers",
  "Hike percentage for engineers",
  "Hike percentage for managers",
  "Hike percentage for HR",
  "Hike percentage for doctors",
  "Hike percentage for nurses",
  "Hike percentage for executives",
  "Hike percentage for sales",
  "Hike percentage for finance",
  "Hike percentage for marketing",
  "Hike percentage for consultants",
  "Hike percentage for BPO",
  "Hike percentage for MNC",
  "Hike percentage for startups",
  "Hike percentage for banking",
  "Hike percentage for insurance",
  "Hike percentage for telecom",
  "Hike percentage for pharma",
  "Hike percentage for legal",
  "Hike percentage for admin",
  "Hike percentage for support staff",
  "Hike percentage for contract employees",
  "Hike percentage for permanent employees",
  "Hike percentage for probation",
  "Hike percentage for interns",
  "Hike percentage for part-time",
  "Hike percentage for full-time",
  "Hike percentage for remote jobs",
  "Hike percentage for on-site jobs",
  "Hike percentage for hybrid jobs",
  "Hike percentage for women",
  "Hike percentage for men",
  "Hike percentage for non-binary",
  "Hike percentage for disabled",
  "Hike percentage for veterans",
  "Hike percentage for minorities",
  "Hike percentage for expats",
  "Hike percentage for NRI",
  "Hike percentage for overseas jobs",
  "Hike percentage for local jobs",
  "Hike percentage for government sector",
  "Hike percentage for PSU",
  "Hike percentage for central government",
  "Hike percentage for state government",
  "Hike percentage for defense",
  "Hike percentage for police",
  "Hike percentage for army",
  "Hike percentage for navy",
  "Hike percentage for air force",
  "Hike percentage for paramilitary",
  "Hike percentage for teachers in India",
  "Hike percentage for professors",
  "Hike percentage for principals",
  "Hike percentage for school staff",
  "Hike percentage for college staff",
  "Hike percentage for university staff",
  "Hike percentage for research staff",
  "Hike percentage for scientists",
  "Hike percentage for IT companies",
  "Hike percentage for software engineers",
  "Hike percentage for developers",
  "Hike percentage for testers",
  "Hike percentage for designers",
  "Hike percentage for architects",
  "Hike percentage for project managers",
  "Hike percentage for product managers",
  "Hike percentage for business analysts",
  "Hike percentage for consultants in India",
  "Hike percentage for freelancers",
  "Hike percentage for gig workers",
  "Hike percentage for blue collar",
  "Hike percentage for white collar",
  "Hike percentage for pink collar",
  "Hike percentage for green collar",
  "Hike percentage for gold collar",
  "Hike percentage for silver collar",
  "Hike percentage for retirees",
  "Hike percentage for pensioners",
  "Hike percentage for self-employed",
  "Hike percentage for entrepreneurs",
  "Hike percentage for business owners",
  "Hike percentage for startups in India"
];

export const workExperienceKeywords = [
  "Work experience calculator",
  "Work experience tracker",
  "Work experience log",
  "Work experience in months",
  "Work experience in years",
  "Work experience in days",
  "Work experience for resume",
  "Work experience for freshers",
  "Work experience for experienced",
  "Work experience for government jobs",
  "Work experience for private jobs",
  "Work experience for IT",
  "Work experience for teachers",
  "Work experience for engineers",
  "Work experience for managers",
  "Work experience for HR",
  "Work experience for doctors",
  "Work experience for nurses",
  "Work experience for executives",
  "Work experience for sales",
  "Work experience for finance",
  "Work experience for marketing",
  "Work experience for consultants",
  "Work experience for BPO",
  "Work experience for MNC",
  "Work experience for startups",
  "Work experience for banking",
  "Work experience for insurance",
  "Work experience for telecom",
  "Work experience for pharma",
  "Work experience for legal",
  "Work experience for admin",
  "Work experience for support staff",
  "Work experience for contract employees",
  "Work experience for permanent employees",
  "Work experience for probation",
  "Work experience for interns",
  "Work experience for part-time",
  "Work experience for full-time",
  "Work experience for remote jobs",
  "Work experience for on-site jobs",
  "Work experience for hybrid jobs",
  "Work experience for women",
  "Work experience for men",
  "Work experience for non-binary",
  "Work experience for disabled",
  "Work experience for veterans",
  "Work experience for minorities",
  "Work experience for expats",
  "Work experience for NRI",
  "Work experience for overseas jobs",
  "Work experience for local jobs",
  "Work experience for government sector",
  "Work experience for PSU",
  "Work experience for central government",
  "Work experience for state government",
  "Work experience for defense",
  "Work experience for police",
  "Work experience for army",
  "Work experience for navy",
  "Work experience for air force",
  "Work experience for paramilitary",
  "Work experience for teachers in India",
  "Work experience for professors",
  "Work experience for principals",
  "Work experience for school staff",
  "Work experience for college staff",
  "Work experience for university staff",
  "Work experience for research staff",
  "Work experience for scientists",
  "Work experience for IT companies",
  "Work experience for software engineers",
  "Work experience for developers",
  "Work experience for testers",
  "Work experience for designers",
  "Work experience for architects",
  "Work experience for project managers",
  "Work experience for product managers",
  "Work experience for business analysts",
  "Work experience for consultants in India",
  "Work experience for freelancers",
  "Work experience for gig workers",
  "Work experience for blue collar",
  "Work experience for white collar",
  "Work experience for pink collar",
  "Work experience for green collar",
  "Work experience for gold collar",
  "Work experience for silver collar",
  "Work experience for retirees",
  "Work experience for pensioners",
  "Work experience for self-employed",
  "Work experience for entrepreneurs",
  "Work experience for business owners",
  "Work experience for startups in India"
];

export const lwdChecklistKeywords = [
  "LWD checklist",
  "Last working day checklist",
  "LWD checklist for employees",
  "LWD checklist for HR",
  "LWD checklist for managers",
  "LWD checklist for IT",
  "LWD checklist for freshers",
  "LWD checklist for experienced",
  "LWD checklist for government employees",
  "LWD checklist for private sector",
  "LWD checklist for teachers",
  "LWD checklist for engineers",
  "LWD checklist for doctors",
  "LWD checklist for nurses",
  "LWD checklist for executives",
  "LWD checklist for sales",
  "LWD checklist for finance",
  "LWD checklist for marketing",
  "LWD checklist for consultants",
  "LWD checklist for BPO",
  "LWD checklist for MNC",
  "LWD checklist for startups",
  "LWD checklist for banking",
  "LWD checklist for insurance",
  "LWD checklist for telecom",
  "LWD checklist for pharma",
  "LWD checklist for legal",
  "LWD checklist for admin",
  "LWD checklist for support staff",
  "LWD checklist for contract employees",
  "LWD checklist for permanent employees",
  "LWD checklist for probation",
  "LWD checklist for interns",
  "LWD checklist for part-time",
  "LWD checklist for full-time",
  "LWD checklist for remote jobs",
  "LWD checklist for on-site jobs",
  "LWD checklist for hybrid jobs",
  "LWD checklist for women",
  "LWD checklist for men",
  "LWD checklist for non-binary",
  "LWD checklist for disabled",
  "LWD checklist for veterans",
  "LWD checklist for minorities",
  "LWD checklist for expats",
  "LWD checklist for NRI",
  "LWD checklist for overseas jobs",
  "LWD checklist for local jobs",
  "LWD checklist for government sector",
  "LWD checklist for PSU",
  "LWD checklist for central government",
  "LWD checklist for state government",
  "LWD checklist for defense",
  "LWD checklist for police",
  "LWD checklist for army",
  "LWD checklist for navy",
  "LWD checklist for air force",
  "LWD checklist for paramilitary",
  "LWD checklist for teachers in India",
  "LWD checklist for professors",
  "LWD checklist for principals",
  "LWD checklist for school staff",
  "LWD checklist for college staff",
  "LWD checklist for university staff",
  "LWD checklist for research staff",
  "LWD checklist for scientists",
  "LWD checklist for IT companies",
  "LWD checklist for software engineers",
  "LWD checklist for developers",
  "LWD checklist for testers",
  "LWD checklist for designers",
  "LWD checklist for architects",
  "LWD checklist for project managers",
  "LWD checklist for product managers",
  "LWD checklist for business analysts",
  "LWD checklist for consultants in India",
  "LWD checklist for freelancers",
  "LWD checklist for gig workers",
  "LWD checklist for blue collar",
  "LWD checklist for white collar",
  "LWD checklist for pink collar",
  "LWD checklist for green collar",
  "LWD checklist for gold collar",
  "LWD checklist for silver collar",
  "LWD checklist for retirees",
  "LWD checklist for pensioners",
  "LWD checklist for self-employed",
  "LWD checklist for entrepreneurs",
  "LWD checklist for business owners",
  "LWD checklist for startups in India"
];

export const gratuityCalculatorKeywords = [
  "Gratuity calculator",
  "Gratuity calculation formula",
  "Gratuity eligibility calculator",
  "Gratuity rules India",
  "Gratuity act India",
  "Gratuity for private employees",
  "Gratuity for government employees",
  "Gratuity for teachers",
  "Gratuity for IT employees",
  "Gratuity for managers",
  "Gratuity for HR",
  "Gratuity for doctors",
  "Gratuity for nurses",
  "Gratuity for executives",
  "Gratuity for sales",
  "Gratuity for finance",
  "Gratuity for marketing",
  "Gratuity for consultants",
  "Gratuity for BPO",
  "Gratuity for MNC",
  "Gratuity for startups",
  "Gratuity for banking",
  "Gratuity for insurance",
  "Gratuity for telecom",
  "Gratuity for pharma",
  "Gratuity for legal",
  "Gratuity for admin",
  "Gratuity for support staff",
  "Gratuity for contract employees",
  "Gratuity for permanent employees",
  "Gratuity for probation",
  "Gratuity for interns",
  "Gratuity for part-time",
  "Gratuity for full-time",
  "Gratuity for remote jobs",
  "Gratuity for on-site jobs",
  "Gratuity for hybrid jobs",
  "Gratuity for women",
  "Gratuity for men",
  "Gratuity for non-binary",
  "Gratuity for disabled",
  "Gratuity for veterans",
  "Gratuity for minorities",
  "Gratuity for expats",
  "Gratuity for NRI",
  "Gratuity for overseas jobs",
  "Gratuity for local jobs",
  "Gratuity for government sector",
  "Gratuity for PSU",
  "Gratuity for central government",
  "Gratuity for state government",
  "Gratuity for defense",
  "Gratuity for police",
  "Gratuity for army",
  "Gratuity for navy",
  "Gratuity for air force",
  "Gratuity for paramilitary",
  "Gratuity for teachers in India",
  "Gratuity for professors",
  "Gratuity for principals",
  "Gratuity for school staff",
  "Gratuity for college staff",
  "Gratuity for university staff",
  "Gratuity for research staff",
  "Gratuity for scientists",
  "Gratuity for IT companies",
  "Gratuity for software engineers",
  "Gratuity for developers",
  "Gratuity for testers",
  "Gratuity for designers",
  "Gratuity for architects",
  "Gratuity for project managers",
  "Gratuity for product managers",
  "Gratuity for business analysts",
  "Gratuity for consultants in India",
  "Gratuity for freelancers",
  "Gratuity for gig workers",
  "Gratuity for blue collar",
  "Gratuity for white collar",
  "Gratuity for pink collar",
  "Gratuity for green collar",
  "Gratuity for gold collar",
  "Gratuity for silver collar",
  "Gratuity for retirees",
  "Gratuity for pensioners",
  "Gratuity for self-employed",
  "Gratuity for entrepreneurs",
  "Gratuity for business owners",
  "Gratuity for startups in India"
];

export const leaveEncashmentKeywords = [
  "Leave encashment calculator",
  "Leave encashment rules",
  "Leave encashment tax exemption",
  "Leave encashment formula",
  "Leave encashment for private employees",
  "Leave encashment for government employees",
  "Leave encashment for teachers",
  "Leave encashment for IT employees",
  "Leave encashment for managers",
  "Leave encashment for HR",
  "Leave encashment for doctors",
  "Leave encashment for nurses",
  "Leave encashment for executives",
  "Leave encashment for sales",
  "Leave encashment for finance",
  "Leave encashment for marketing",
  "Leave encashment for consultants",
  "Leave encashment for BPO",
  "Leave encashment for MNC",
  "Leave encashment for startups",
  "Leave encashment for banking",
  "Leave encashment for insurance",
  "Leave encashment for telecom",
  "Leave encashment for pharma",
  "Leave encashment for legal",
  "Leave encashment for admin",
  "Leave encashment for support staff",
  "Leave encashment for contract employees",
  "Leave encashment for permanent employees",
  "Leave encashment for probation",
  "Leave encashment for interns",
  "Leave encashment for part-time",
  "Leave encashment for full-time",
  "Leave encashment for remote jobs",
  "Leave encashment for on-site jobs",
  "Leave encashment for hybrid jobs",
  "Leave encashment for women",
  "Leave encashment for men",
  "Leave encashment for non-binary",
  "Leave encashment for disabled",
  "Leave encashment for veterans",
  "Leave encashment for minorities",
  "Leave encashment for expats",
  "Leave encashment for NRI",
  "Leave encashment for overseas jobs",
  "Leave encashment for local jobs",
  "Leave encashment for government sector",
  "Leave encashment for PSU",
  "Leave encashment for central government",
  "Leave encashment for state government",
  "Leave encashment for defense",
  "Leave encashment for police",
  "Leave encashment for army",
  "Leave encashment for navy",
  "Leave encashment for air force",
  "Leave encashment for paramilitary",
  "Leave encashment for teachers in India",
  "Leave encashment for professors",
  "Leave encashment for principals",
  "Leave encashment for school staff",
  "Leave encashment for college staff",
  "Leave encashment for university staff",
  "Leave encashment for research staff",
  "Leave encashment for scientists",
  "Leave encashment for IT companies",
  "Leave encashment for software engineers",
  "Leave encashment for developers",
  "Leave encashment for testers",
  "Leave encashment for designers",
  "Leave encashment for architects",
  "Leave encashment for project managers",
  "Leave encashment for product managers",
  "Leave encashment for business analysts",
  "Leave encashment for consultants in India",
  "Leave encashment for freelancers",
  "Leave encashment for gig workers",
  "Leave encashment for blue collar",
  "Leave encashment for white collar",
  "Leave encashment for pink collar",
  "Leave encashment for green collar",
  "Leave encashment for gold collar",
  "Leave encashment for silver collar",
  "Leave encashment for retirees",
  "Leave encashment for pensioners",
  "Leave encashment for self-employed",
  "Leave encashment for entrepreneurs",
  "Leave encashment for business owners",
  "Leave encashment for startups in India"
];

export const ctcVsInHandKeywords = [
  "CTC vs InHand calculator",
  "CTC vs InHand salary calculator",
  "CTC vs InHand difference",
  "CTC vs InHand salary India",
  "CTC vs InHand salary formula",
  "CTC vs InHand salary meaning",
  "CTC vs InHand salary breakup",
  "CTC vs InHand salary structure",
  "CTC vs InHand salary for freshers",
  "CTC vs InHand salary for experienced",
  "CTC vs InHand salary for government employees",
  "CTC vs InHand salary for private sector",
  "CTC vs InHand salary for teachers",
  "CTC vs InHand salary for engineers",
  "CTC vs InHand salary for managers",
  "CTC vs InHand salary for HR",
  "CTC vs InHand salary for doctors",
  "CTC vs InHand salary for nurses",
  "CTC vs InHand salary for executives",
  "CTC vs InHand salary for sales",
  "CTC vs InHand salary for finance",
  "CTC vs InHand salary for marketing",
  "CTC vs InHand salary for consultants",
  "CTC vs InHand salary for BPO",
  "CTC vs InHand salary for MNC",
  "CTC vs InHand salary for startups",
  "CTC vs InHand salary for banking",
  "CTC vs InHand salary for insurance",
  "CTC vs InHand salary for telecom",
  "CTC vs InHand salary for pharma",
  "CTC vs InHand salary for legal",
  "CTC vs InHand salary for admin",
  "CTC vs InHand salary for support staff",
  "CTC vs InHand salary for contract employees",
  "CTC vs InHand salary for permanent employees",
  "CTC vs InHand salary for probation",
  "CTC vs InHand salary for interns",
  "CTC vs InHand salary for part-time",
  "CTC vs InHand salary for full-time",
  "CTC vs InHand salary for remote jobs",
  "CTC vs InHand salary for on-site jobs",
  "CTC vs InHand salary for hybrid jobs",
  "CTC vs InHand salary for women",
  "CTC vs InHand salary for men",
  "CTC vs InHand salary for non-binary",
  "CTC vs InHand salary for disabled",
  "CTC vs InHand salary for veterans",
  "CTC vs InHand salary for minorities",
  "CTC vs InHand salary for expats",
  "CTC vs InHand salary for NRI",
  "CTC vs InHand salary for overseas jobs",
  "CTC vs InHand salary for local jobs",
  "CTC vs InHand salary for government sector",
  "CTC vs InHand salary for PSU",
  "CTC vs InHand salary for central government",
  "CTC vs InHand salary for state government",
  "CTC vs InHand salary for defense",
  "CTC vs InHand salary for police",
  "CTC vs InHand salary for army",
  "CTC vs InHand salary for navy",
  "CTC vs InHand salary for air force",
  "CTC vs InHand salary for paramilitary",
  "CTC vs InHand salary for teachers in India",
  "CTC vs InHand salary for professors",
  "CTC vs InHand salary for principals",
  "CTC vs InHand salary for school staff",
  "CTC vs InHand salary for college staff",
  "CTC vs InHand salary for university staff",
  "CTC vs InHand salary for research staff",
  "CTC vs InHand salary for scientists",
  "CTC vs InHand salary for IT companies",
  "CTC vs InHand salary for software engineers",
  "CTC vs InHand salary for developers",
  "CTC vs InHand salary for testers",
  "CTC vs InHand salary for designers",
  "CTC vs InHand salary for architects",
  "CTC vs InHand salary for project managers",
  "CTC vs InHand salary for product managers",
  "CTC vs InHand salary for business analysts",
  "CTC vs InHand salary for consultants in India",
  "CTC vs InHand salary for freelancers",
  "CTC vs InHand salary for gig workers",
  "CTC vs InHand salary for blue collar",
  "CTC vs InHand salary for white collar",
  "CTC vs InHand salary for pink collar",
  "CTC vs InHand salary for green collar",
  "CTC vs InHand salary for gold collar",
  "CTC vs InHand salary for silver collar",
  "CTC vs InHand salary for retirees",
  "CTC vs InHand salary for pensioners",
  "CTC vs InHand salary for self-employed",
  "CTC vs InHand salary for entrepreneurs",
  "CTC vs InHand salary for business owners",
  "CTC vs InHand salary for startups in India"
];
