export const daysArr = [30, 60, 90];

export const routes = [
  { path: "/notice-period", label: "Notice Period" },
  { path: "/salary-hike", label: "Salary Hike" },
  { path: "/hike-percentage", label: "Hike Percentage" },
  { path: "/work-experience", label: "Work Experience" },
  { path: "/lwd-checklist", label: "LWD Checklist" },
  { path: "/gratuity", label: "Gratuity Calculator" },
  { path: "/leave-encashment", label: "Leave Encashment" },
];

export const frequentQuestions = [
  "Can my notice period be reduced or waived?",
  "Do I need to serve the full notice period?",
  "What happens if I resign without serving the notice period?",
  "Can I use my remaining leave balance during my notice period?",
  "Will I receive my full salary and benefits during the notice period?",
  "Can my employer extend my notice period?",
  "What should I do if my employer is not accepting my resignation?",
  "Will I get my full & final settlement immediately after my last working day?",
  "Can I join a new company during my notice period?",
  "Can my employer force me to work during my notice period even if I have no tasks assigned?",
];

export const SEO_KEYWORDS = [
  "WorkWise",
  "career calculator",
  "notice period calculator",
  "last working day calculator",
  "salary hike estimator",
  "work experience tracker",
  "job resignation tools",
  "job notice period tracker",
  "final working day calculator",
  "salary increment predictor",
  "work anniversary calculator",
  "employment duration calculator",
  "job transition planning",
  "career growth tracker",
  "resignation date calculator",
  "salary negotiation tips",
  "salary growth projection",
  "salary raise estimation",
  "experience certificate tracker",
  "employee resignation helper",
  "notice period extension calculator",
  "HR resignation management",
  "last working day notice",
  "corporate job resignations",
  "job change calculator",
  "salary comparison tool",
  "employee benefits calculator",
  "employment resignation tracker",
  "job leave date calculator",
  "professional career tools",
  "notice period completion",
  "salary planning app",
  "HR job tracking tools",
  "job switch planning",
  "career progression estimator",
  "exit interview preparation",
  "job exit date finder",
  "career decision-making tool",
  "best salary hike tool",
  "salary hike calculation formula",
  "last day of employment tracker",
  "monthly salary raise estimation",
  "employment period estimation",
  "resignation process guide",
  "job resignation planning tool",
  "work experience log",
  "career management platform",
  "career timeline tracker",
  "best career growth calculator",
  "career development planning",
  "HR software for resignations",
  "work history tracker",
  "employment gap calculator",
  "pay raise prediction",
  "compensation increase estimator",
  "financial career planning",
  "salary increment predictor",
  "long-term salary growth",
  "job resignation checklist",
  "best salary raise calculator",
  "professional resignation tools",
  "salary forecast for employees",
  "job change decision-making",
  "work duration estimator",
  "career performance metrics",
  "last day at work estimation",
  "salary appraisal predictor",
  "pay scale evolution",
  "employee transition planning",
  "work tenure calculator",
  "resignation timeline planning",
  "employment tenure tracker",
  "next job salary comparison",
  "HR employee exit tracking",
  "career forecasting calculator",
  "retirement planning estimator",
  "work notice period management",
  "pay raise planning guide",
  "career switch strategy",
  "employment verification tool",
  "corporate resignation strategy",
  "salary improvement planning",
  "job resignation tool online",
  "job market analysis tool",
  "salary package comparison",
  "workforce transition calculator",
  "job shift strategy calculator",
  "employment exit date planner",
  "career performance tracking app",
  "salary adjustment forecast",
  "work history verification",
  "employment planning software",
  "career salary tracker",
  "job benefits assessment",
  "resignation planning software",
  "pay increase calculator",
  "workforce mobility tools",
  "career stability estimation",
  "resignation strategy app",
  "employee career roadmaps",
  "financial job tracking",
  "salary evaluation for professionals",
  "corporate employment tools",
  "HR payroll forecasting",
  "career decision support tool",
  "notice period tracker",
  "last working day estimator",
  "resignation planning calculator",
  "notice period completion guide",
  "salary hike percentage calculator",
  "expected salary raise predictor",
  "salary growth rate calculator",
  "work experience duration calculator",
  "career milestone tracker",
  "employee service length estimator",
  "LWD checklist for employees",
  "last working day process",
  "HR notice period policies",
  "gratuity eligibility checker",
  "gratuity calculation formula",
  "retirement benefits estimator",
  "final settlement calculator",
  "job exit process tracker",
  "HR resignation formalities",
  "career transition planning tool",
  "employment benefits tracker",
  "gratuity payout estimator",
  "work history documentation",
  "HR compliance resignation guide",
  "final paycheck estimation",
  "gratuity claim process",
  "employee exit benefits",
  "severance pay calculator",
  "work tenure benefits estimator",
  "job exit financial planning",
  "gratitude calculator",
];

export const LWD_CHECKLIST = {
  "Before Resigning": [
    "If leaving to go to another company, make sure you have the offer letter in hand.",
    "Print and save important documents like PF UAN, Form 16, tax-related files, and at least 3 months pay slips for future reference.",
    "File any expenses, claims, and reports.",
    "Write a short transition document on projects/accounts you are working on.",
    "Gradually start taking home personal items that are in the office.",
    "Draft your resignation mail/letter in advance.",
  ],
  "Day of Resigning / Serving Notice Period": [
    "Schedule 1-to-1 time with your boss/HR.",
    "Know your notice period and send your resignation mail/letter appropriately.",
    "Agree on your last working day with your boss and HR.",
    "Hand over all your pending tasks or KT to respective collegues.",
    "Continue delivering quality work to leave a lasting positive impression.",
    "Wipe personal information from the laptop and keep backup of you files",
    "Complete your exit interview with your superiors and/or the HR department",
    "Create a list of people you want to talk to in- before leaving.",
    "Collect collegues contacts and network with you collegues for future references",
    "Submit company possessions such as locker keys, ID card, laptop, etc., on your last day.",
    "Send farewell emails.",
  ],
  "After Resigning": [
    "Address important administrative tasks. Ex: Medical Insurance",
    "Follow up with HR for documentation and follow up on outstanding pay and expenses.",
    "Ask for a letter of recommendation from your manager",
    "Update LinkedIn and other social media profiles.",
  ],
};
